=== einen Renderkontext erstellen
Der Renderkontext wird mithilfe der GLFW Bibliothek erstellt.
Die Dokumentation dazu findet man unter https://www.glfw.org/documentation.html["Dokumentation GLFW",window=_blank].

.Initialisierung von GLFW
[source%autofit,c++,numbered]
----
#include <stdexcept>

#include <glad/glad.h>
#include <GLFW/glfw3.h>

...

if (!glfwInit()) {
    throw std::runtime_error("glfwInit() fails");
}
----

Am Ende des Programmes wird diese Bibliothek mittels der Funktion glfwTerminate() wieder freigegeben.

.Deinitialisierung von GLFW
[source%autofit,c++,numbered]
----
glfwTerminate();
----

Im nächsten Schritt werden die Eigenschaften für den Renderkontext festgelegt.

.festlegen der Eigenschaften des Renderkontextes
[source%autofit,c++,numbered]
----
uint32_t gl_major{4};
uint32_t gl_minor{6};
uint32_t gl_samples{8};

glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, gl_major); <1>
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, gl_minor); <2>
glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
glfwWindowHint(GLFW_SAMPLES, gl_samples); <3>
glfwWindowHint(GLFW_VISIBLE, GLFW_TRUE);
----

<1> OpenGL Hauptversion
<2> OpenGL Unterversion
<3> Anzahl der MSAA (Multisampling Anti-Aliasing) Samples

Anschließend kann das Renderfenster erstellt werden, und der zugehörige Kontext als aktuell gesetzt werden.

.Fenster erstellen und Kontext aktuell setzen
[source%autofit,c++,numbered]
----
GLFWwindow *window = glfwCreateWindow(width, height,
                            title.c_str(),
                            fullscreen ? glfwGetPrimaryMonitor() : nullptr, nullptr);
if (!window) {
    glfwTerminate();
    throw std::runtime_error("glfwCreateWindow() fails");
}

glfwMakeContextCurrent(window);
----

Um den vollen Funktionsumfang von OpenGL zu nutzen, ist es erforderlich diese Funktionsaufrufe zu laden.
Dies erledigt die Bibliothek GLAD.

.GLAD initialisieren
[source%autofit,c++,numbered]
----
if (!gladLoadGLLoader(reinterpret_cast<GLADloadproc>(glfwGetProcAddress))) {
    glfwTerminate();
    throw std::runtime_error("GLAD Init() fails");
}
----

.Zeichenschleife
[source%autofit,c++,numbered]
----
while (!glfwWindowShouldClose(window)) {
    /* zeichnen */
    glClear(GL_COLOR_BUFFER_BIT);

    ...

    /* Hintergrundpuffer und Vordergrundpuffer tauschen */
    glfwSwapBuffers(window);

    /* Ereignisse abholen */
    glfwPollEvents();
}
----

Der vollständige Quelltext befindet sich link:main.cpp[hier].